### ISSUE TITLE
Repo confusion

### ISSUE THREAD

**Issue by mhils** [mitmproxy/docker-base#6]
![image](https://cloud.githubusercontent.com/assets/1019198/15000697/98f6338a-1146-11e6-8920-840dd1f4a077.png)

Maybe I'm just not a Docker person, but I find this very confusing that we have both `mitmproxy/mitmproxy` and `mitmproxy/releases`. It doesn't help that a search for "mitmproxy" lists the mitmproxy/mitmproxy repo first and a few unrelated ones below.

How about the following?

- [x] <s>Unlist mitmproxy/mitmproxy repo from Dockerhub</s>
- [x] Unlist mitmproxy/base
- [x] In mitmproxy/releases provide `$tag`,  `latest` and `dev`, with `latest` pointing to ther latest tag, `dev` pointing to the GitHub version. 
- [x] <s>Get Dockerhub to make mitmproxy/releases the [official "mitmproxy" repo](https://docs.docker.com/docker-hub/official_repos/)</s>

**Comment by mhils** [comment]
@cortesi @dweinstein @wernight: Are there any objections against deleting the mitmproxy/mitmproxy and mitmproxy/base repositories from Dockerhub? 

If noone complains, I will remove them in a week.

**Comment by wernight** [comment]
`mitmproxy/mitmproxy` sounds a better name than `mitmproxy/releases`. The first is the group, the second should be the product.

**Comment by mhils** [comment]
I agree, but unfortunately there's https://github.com/docker/hub-feedback/issues/313. I wonder if we can just delete the repo and re-create it? What would that break?

**Comment by wernight** [comment]
Yes that should work.

Le mar. 17 mai 2016 21:21, Maximilian Hils <notifications@github.com> a
écrit :

**Comment by mhils** [comment]
Fixed!
